// <auto-generated />
using ControleEscolar.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleEscolar.Migrations
{
    [DbContext(typeof(AlunoContext))]
    [Migration("20231027164215_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("ControleEscolar.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Idade")
                        .HasColumnType("INTEGER")
                        .HasColumnName("idade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<float>("NotaPrimeiroSemestre")
                        .HasColumnType("REAL")
                        .HasColumnName("primeiro_semestre");

                    b.Property<float>("NotaSegundoSemestre")
                        .HasColumnType("REAL")
                        .HasColumnName("segundo_semestre");

                    b.Property<string>("Professor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("professor");

                    b.Property<int>("Sala")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sala");

                    b.HasKey("Id");

                    b.ToTable("alunos");
                });
#pragma warning restore 612, 618
        }
    }
}
